# -*- coding: utf-8 -*-
"""btc3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12P9NQ9G7WkgIZFlM-si_0RH2eD09wrJD

CÂU 2:
"""

import pandas as pd
from scipy.stats import chi2_contingency

# Dữ liệu Car vs Category
car_data = pd.DataFrame({
    'Car': ['A', 'A', 'B', 'B', 'B', 'C', 'C'],
    'Category': ['Low', 'Medium', 'High', 'Low', 'Medium', 'Low', 'Medium'],
    'Frequency': [1, 3, 2, 1, 1, 1, 3]
})

car_table = car_data.pivot_table(index='Car', columns='Category', values='Frequency', fill_value=0)
print("Bảng tần suất (Car vs Category):\n", car_table)

# Thực hiện kiểm định Chi bình phương
chi2_car, p_car, dof_car, expected_car = chi2_contingency(car_table)
print("\nKết quả kiểm định Chi-square cho Car:")
print(f"Chi2 statistic = {chi2_car:.4f}")
print(f"p-value = {p_car:.4f}")

# Dữ liệu Day vs Category
day_data = pd.DataFrame({
    'Day': ['Day 1', 'Day 1', 'Day 2', 'Day 2', 'Day 3', 'Day 3', 'Day 4', 'Day 4'],
    'Category': ['High', 'Medium', 'High', 'Medium', 'Low', 'Medium', 'Low', 'Medium'],
    'Frequency': [1, 2, 1, 2, 1, 2, 2, 1]
})

day_table = day_data.pivot_table(index='Day', columns='Category', values='Frequency', fill_value=0)
print("\nBảng tần suất (Day vs Category):\n", day_table)

# Thực hiện kiểm định Chi bình phương
chi2_day, p_day, dof_day, expected_day = chi2_contingency(day_table)
print("\nKết quả kiểm định Chi-square cho Day:")
print(f"Chi2 statistic = {chi2_day:.4f}")
print(f"p-value = {p_day:.4f}")

"""- Dựa trên kiểm định Chi bình phương giữa các mẫu xe và phân loại điểm số, kết quả cho thấy không có sự khác biệt giữa các mẫu A, B, và C trong suốt 4 ngày thử nghiệm (vì p = 0.273 > 0.05).

- Kết quả thử nghiệm không phụ thuộc vào ngày cũng không phụ thuộc vào mẫu xe (vì cả hai p-value đều > 0.05)
"""